version: '3'

services:
  httpd:
    build: .
    restart: always
    networks:
      - web
    expose:
      - "80"
    environment:
      - SERVER_NAMES=njudung.etnolit.se
    volumes:
      - /srv/html:/var/www/html
      - /srv/dav:/var/lib/dav
      - ${PWD}/user.json:/user.json
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.httpd.frontend.rule=Host:njudung.etnolit.se"
      - "traefik.httpd.port=80"
      - "traefik.httpd.protocol=http"

networks:
  web:
    external: true
