version: '3'

services:
  httpd:
    build:
      context: .
      dockerfile: httpd/Dockerfile
    restart: always
    networks:
      - web
      - backend
    expose:
      - "80"
    environment:
      - SERVER_NAMES=njudung.etnolit.se
    volumes:
      - /srv/html:/var/www/html
      - /srv/dav:/var/lib/dav
      - ${PWD}/user.json:/user.json
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.httpd.frontend.rule=Host:njudung.etnolit.se"
      - "traefik.httpd.port=80"
      - "traefik.httpd.protocol=http"
      - "traefik.httpd-dav.frontend.rule=Host:dav.njudung.etnolit.se"
      - "traefik.httpd-dav.port=80"
      - "traefik.httpd-dav.protocol=http"
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    restart: always
    networks:
      - backend
    expose:
      - "9000"
    volumes:
      - /srv/html:/var/www/html
      - /srv/dav/data:/var/lib/dav/data
    user: "82:82"
  db:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    restart: always
    networks:
      - backend
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /srv/mariadb:/var/lib/mysql
      - ${PWD}/user.json:/user.json

networks:
  web:
    external: true
  backend:
